# Imports

In [169]:
import numpy as np
import pandas as pd

#creating dataset

In [144]:
data = {
    "area": [800, 1000, 1200, 1500, 1800, 2000, 2200, 2500, 2800, 3000],
    "bedroom": [2, 2, 3, 3, 3, 4, 4, 4, 5, 5],
    "bathroom": [1, 2, 2, 2, 3, 3, 3, 4, 4, 5],
    "price": [35, 45, 55, 65, 80, 95, 110, 125, 145, 165]
}

df = pd.DataFrame(data)
df.head()

   area  bedroom  bathroom  price
0   800        2         1     35
1  1000        2         2     45
2  1200        3         2     55
3  1500        3         2     65
4  1800        3         3     80

In [145]:
X = df.iloc[:,0:3]
y = df.iloc[:,-1]

In [146]:
X.head()

   area  bedroom  bathroom
0   800        2         1
1  1000        2         2
2  1200        3         2
3  1500        3         2
4  1800        3         3

In [147]:
y.head()

0    35
1    45
2    55
3    65
4    80
Name: price, dtype: int64

## Using Sklearn's Linear Regression

In [148]:
from sklearn.model_selection import train_test_split

In [149]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [150]:
print(X_train.shape)
print(X_test.shape)

(8, 3)
(2, 3)

In [151]:
from sklearn.linear_model import LinearRegression

In [152]:
reg = LinearRegression()

In [153]:
reg.fit(X_train,y_train)

LinearRegression()

In [154]:
y_pred = reg.predict(X_test)

In [155]:
from sklearn.metrics import r2_score

In [156]:
r2_score(y_test,y_pred)

0.8223852040816344

In [157]:
reg.coef_

array([0.04375   , 0.41666667, 8.33333333])

In [158]:
reg.intercept_

np.float64(-14.687500000000355)

## Making our own Linear Regression Class

betas = <br>
np.linalg.<br>
inv(np.dot(X_train.T,X_train))<br>
.dot(X_train.T)<br>
.dot(y_train)<br>

In [159]:
class NITR_MLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)  # adding a column (beta 0) at index 0

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [160]:
lr = NITR_MLR()

In [161]:
lr.fit(X_train,y_train)

In [162]:
X_train.shape

(8, 3)

In [163]:
np.insert(X_train,0,1,axis=1).shape

(8, 4)

In [164]:
y_pred = lr.predict(X_test)

In [165]:
mse = np.mean((y_test - y_pred) ** 2)
mae = np.mean((y_test - y_pred))
r2 = 1 - (mse)/np.mean((y_test - np.average(y_test))**2)
mse,mae,r2

(np.float64(54.39453124992267),
 np.float64(-5.937499999993676),
 np.float64(0.8223852040818851))

In [166]:
r2_score(y_test,y_pred)

0.8223852040818851

#compare NITR_MLR and skLearn

In [167]:
lr.coef_,reg.coef_

(array([0.04375   , 0.41666667, 8.33333333]),
 array([0.04375   , 0.41666667, 8.33333333]))

In [168]:
lr.intercept_,reg.intercept_

(np.float64(-14.687500000005059), np.float64(-14.687500000000355))