#import

In [134]:
import numpy as np
import pandas as pd

In [135]:
import seaborn as sns
import matplotlib as plt

#customer dataset

In [136]:
df = pd.read_csv('/content/customer.csv')

In [137]:
df.shape

(50, 5)

In [138]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

#'review' and 'education' should be encoded(ordinal) and purchased should be encoded Label

In [139]:
df = df.iloc[:,2:]
df.sample(5)

     review education purchased
28     Poor    School        No
40     Good    School        No
46     Poor        PG        No
4   Average        UG        No
17     Poor        UG       Yes

#train test split

In [140]:
from sklearn.model_selection import train_test_split

In [141]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['purchased'],axis=1),df['purchased'],test_size=0.3,)

In [142]:
x_train.head()

     review education
30  Average        UG
21  Average        PG
15     Poor        UG
42     Good        PG
32  Average        UG

In [143]:
y_train.head()

30     No
21     No
15     No
42    Yes
32    Yes
Name: purchased, dtype: object

#ordinal encoding

In [144]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Good','Average'],['School','UG','PG']])

In [145]:
oe.categories

[['Poor', 'Good', 'Average'], ['School', 'UG', 'PG']]

In [146]:
x_train_trans = oe.fit_transform(x_train)
x_test_trans = oe.transform(x_test)

#setting columns

In [147]:
x_train_trans = pd.DataFrame(x_train_trans,columns = x_train.columns)

In [148]:
print(x_train.head(),
      "\n\n\n\n\n",
x_train_trans.head())

     review education
30  Average        UG
21  Average        PG
15     Poor        UG
42     Good        PG
32  Average        UG




    review  education
0     2.0        1.0
1     2.0        2.0
2     0.0        1.0
3     1.0        2.0
4     2.0        1.0

In [149]:
#x_test_trans = pd.DataFrame(x_test_trans,columns = x_test.columns)

#encode output column

In [150]:
y_train.head()

30     No
21     No
15     No
42    Yes
32    Yes
Name: purchased, dtype: object

#use label encoding for output column

In [151]:
from sklearn.preprocessing import LabelEncoder

In [152]:
le = LabelEncoder()
y_train_trans = le.fit_transform(y_train)

In [153]:
y_train.shape

(35,)

In [154]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [155]:
y_test_trans = le.transform(y_test)

In [156]:
print(y_train.to_numpy())

['No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No']

In [157]:
y_train_trans

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [158]:
y_test_trans

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1])