#import

In [140]:
import numpy as np
import pandas as pd

In [141]:
import seaborn as sns
import matplotlib as plt

#customer dataset

In [142]:
df = pd.read_csv('/content/customer.csv')

In [143]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

#'review' and 'education' should be encoded(ordinal) and purchased should be encoded Label

In [144]:
df = df.iloc[:,2:]
df.sample(5)

     review education purchased
34  Average    School        No
18     Good    School        No
39     Poor        PG        No
28     Poor    School        No
25     Good    School        No

#train test split

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(['purchased'],axis=1),df['purchased'],test_size=0.3,)

In [147]:
x_train.head()

     review education
10     Good        UG
8   Average        UG
7      Poor    School
2      Good        PG
39     Poor        PG

In [148]:
y_train.head()

10    Yes
8      No
7     Yes
2      No
39     No
Name: purchased, dtype: object

#ordinal encoding

In [149]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Good','Average'],['School','UG','PG']])

In [150]:
oe.categories

[['Poor', 'Good', 'Average'], ['School', 'UG', 'PG']]

In [151]:
x_train_trans = oe.fit_transform(x_train)
x_test_trans = oe.transform(x_test)

#setting columns

In [152]:
x_train = pd.DataFrame(x_train,columns = x_train.columns)

In [153]:
x_train.head()

     review education
10     Good        UG
8   Average        UG
7      Poor    School
2      Good        PG
39     Poor        PG

In [154]:
x_test = pd.DataFrame(x_test,columns = x_test.columns)

#encode output column

In [155]:
y_train.head()

10    Yes
8      No
7     Yes
2      No
39     No
Name: purchased, dtype: object

#use label encoding for output column

In [156]:
from sklearn.preprocessing import LabelEncoder

In [157]:
le = LabelEncoder()
y_train_trans = le.fit_transform(y_train)

In [158]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [159]:
y_test_trans = le.transform(y_test)

In [160]:
y_train_trans

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [161]:
y_test_trans

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1])